version: "3"
services:
  
  client:
   build:
      context: ./client
      dockerfile: Dockerfile.dev
   ports:
    -  3000:3000
   container_name: mern-auth-ui
   networks:
    -  mern-network
   volumes:
    -  ./client/src:/usr/app/src
    -  ./client/public:/usr/app/public
   depends_on:
    - server
   stdin_open: true
   tty: true

  server:
   build:
      context: ./server
      dockerfile: Dockerfile.dev
   ports:
     - 5000:5000
   container_name: mern-auth-api
   networks:
     - mern-network
   volumes:
    - ./server/src:/usr/app/src
   depends_on:
    - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - mern-network
    volumes:
      - mongo-data:/data/db

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local