POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "fullName": "Sarah Smith",
  "username": "Sarah",
  "email": "sarah@example.com",
  "password": "123456",
  "confirmPassword": "123456"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email" : "sam@example.com",
  "password" : "123456"
}

###
GET http://localhost:5000/api/user/63b3c6473eb208f33bdd30b5