POST http://localhost:5000/api/register
Content-Type: application/json

{
  "fullName": "Sam Smith",
  "username": "Sam",
  "email": "sam@example.com",
  "password": "123456",
  "confirmPassword": "123456"
}

###
POST http://localhost:5000/api/login
Content-Type: application/json

{
  "email" : "jane@example.com",
  "password" : "123456"
}